### ISSUE TITLE
Questions about gpu

### ISSUE THREAD

**Issue by jingzhang697** [mesnico/ALADIN#1]
hello,
   Recently, I'm doing an experiment in this direction, but I'm worried that gpu resources will not be supported. I would like to ask how much gpu resources are needed after the whole experiment？Hope to help me, thank you.

**Comment by mesnico** [comment]
Hi @jingzhang697, we were able to run both training and inference using a single RTX 2080Ti (12 GB VRAM). If you are considering performing only inference, probably even a smaller GPU would be ok.
